In [1]:
#Name:-Rahul Nyati
#Topic - SVD
#if you like my code and my paper notes then please like my github page Thanks!
#perform SVD(Singular value Decomposiotion) by using Numpy in python programming


In [ ]:
# First we import necessary libaries which we used to solve the problem of singular value decomposition
#Example 1
import numpy as np

In [2]:
#Creating a matrix A
A = np.array([[2,4,3],[6,2,3],[4,7,1]])

In [3]:
print(A)

[[2 4 3]
 [6 2 3]
 [4 7 1]]


In [4]:
#Performing SVD
U, D, VT = np.linalg.svd(A)

In [5]:
print("orthogonal left singular matrix")
print(U)

[[-0.45464173  0.13839803 -0.87985617]
 [-0.55531237 -0.81639288  0.15852706]
 [-0.69636848  0.56066803  0.44802041]]


In [6]:
print("diagonal matrix, which describes the strength of each latent factor ")
print(D)

[11.14258456  3.99080771  1.97895506]


In [8]:
print("orthogonal right singular matrix ka Transpose")
print(VT)

[[-0.63061057 -0.70035556 -0.33441351]
 [-0.59609214  0.7130092  -0.36917753]
 [ 0.49699544 -0.03346599 -0.86710758]]


In [17]:
#Checking if we can remake the original matrix using U,D,VT -
#For matrix multiplication we use @ instead of this -> * 
A_remake = (U @ np.diag(D) @ VT)
print(A_remake)

[[2. 4. 3.]
 [6. 2. 3.]
 [4. 7. 1.]]


In [44]:
#perform SVD(Singular value Decomposiotion) by using sklearn in python programming
#Importing required modules
import numpy as np
from sklearn.utils.extmath import randomized_svd
 
#Creating array
A = np.array([[2,4,3],[6,2,3],[4,7,1]])

In [45]:
#Fitting the SVD class
u, s, vt = randomized_svd(A, n_components = 2)

In [46]:
#Printing the transformed matrix
print("orthogonal left singular matrix")
print(u)

[[ 0.45464173 -0.13839803]
 [ 0.55531237  0.81639288]
 [ 0.69636848 -0.56066803]]


In [47]:
print("diagonal matrix, which describes the strength of each latent factor ")
print(s)

[11.14258456  3.99080771]


In [48]:
print("orthogonal right singular matrix ka Transpose")
print(vt)

[[ 0.63061057  0.70035556  0.33441351]
 [ 0.59609214 -0.7130092   0.36917753]]


In [49]:
#to Recheack
#Checking if we can remake the original matrix using U,D,VT -
#For matrix multiplication we use @ instead of this -> * 
A_remake1 = (u @ np.diag(s) @ vt)
print(A_remake1)

[[2.86536638 3.94172916 1.4901959 ]
 [5.84408363 2.01049888 3.27202719]
 [3.55935775 7.02967136 1.76878821]]


In [34]:
#Our Paper Example
#example no 2
# By USing Numpy
import numpy as np
A = np.array([[2,2],[1,1]])

In [35]:
print(A)

[[2 2]
 [1 1]]


In [36]:
#Performing SVD
U, D, VT = np.linalg.svd(A)

In [29]:
print("orthogonal left singular matrix")
print(U)#1/root(5) tends to 0.4472136 and 2/root(5)tends to 0.89442719

[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]


In [30]:
print("diagonal matrix, which describes the strength of each latent factor ")
print(D)#root 10 which is equvalent to 3.16227766e+00 and 1.10062118e-17-> 0

[3.16227766e+00 1.10062118e-17]


In [32]:
print("orthogonal right singular matrix ka Transpose")
print(VT)#in our example the value are in the form 1/root(2) which is equivalent to =0.70710678 and the sign no matter beacuse the sing of negative multiply by negative is positive

[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [37]:
#Checking if we can remake the original matrix using U,D,VT -
#For matrix multiplication we use @ instead of this -> * 
A_remake = (U @ np.diag(D) @ VT)
print(A_remake)

[[2. 2.]
 [1. 1.]]


In [51]:
#Now we solve by using sklearn
#perform SVD(Singular value Decomposiotion) by using sklearn in python programming
#Importing required modules
import numpy as np
from sklearn.utils.extmath import randomized_svd
 
#Creating array
A = np.array([[2,2],[1,1]])

In [52]:
print(A)

[[2 2]
 [1 1]]


In [53]:
#Fitting the SVD class
u, s, vt = randomized_svd(A, n_components = 2)

In [54]:
print("orthogonal left singular matrix")
print(u)

[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [55]:
print("diagonal matrix, which describes the strength of each latent factor ")
print(s)

[3.16227766 0.        ]


In [56]:
print("orthogonal right singular matrix ka Transpose")
print(vt)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [57]:
A_remake = (u @ np.diag(s) @ vt)
print(A_remake)

[[2. 2.]
 [1. 1.]]
